# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Nylox. <https://github.com/nylox/nylox.git>
#
#    Nylox is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Nylox is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Nylox.  If not, see <http://www.gnu.org/licenses/>.
#

---
- set_fact:
    conf_files:
    - "named.conf"
    - "named.conf.local"
    - "named.conf.options"
    conf_dir:  "/etc/bind"
    username:  "root"
    groupname: "bind"
  tags:
  - always

- name: "Delete '{{ ansible_pkg_mgr }}' based configuration"
  file:
    dest:  "{{ conf_dir }}/{{ item }}"
    state: absent
  with_items:
  - "{{ conf_files }}"
  tags:
  - clear

- name: "Deploy '{{ ansible_pkg_mgr }}' based configuration"
  template:
    src:   "{{ ansible_pkg_mgr }}/{{ item }}.j2"
    dest:  "{{ conf_dir }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode:  "u=rw,g=r,o=r"
    force: yes
  with_items:
  - "{{ conf_files }}"
  tags:
  - conf

- name: "Deploy daemon additional configuration"
  template:
    src:   "./{{ item }}.j2"
    dest:  "/var/cache/bind/{{ item }}"
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode:  "u=rw,g=r,o=r"
    force: yes
  with_items:
  - "domain.zone"
  - "domain.rr.zone"
  tags:
  - conf

- name: "Create logging directory"
  file:
    dest:  "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode:  "u=rwx,g=rwx,o=rx"
  with_items:
  - "/var/lib/bind"
  tags:
  - conf

- name: "Create log file"
  copy:
    dest: "/var/lib/bind/bind.log"
    content: "--- Empty log file ---"
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: "u=rwx,g=rwx,o=rx"
  tags:
  - conf
  - init

- name: "Deploy resolv.conf"
  template:
    src:   "./{{ item }}.j2"
    dest:  "/etc/resolvconf/resolv.conf.d/base"
    owner: "root"
    group: "root"
    mode:  "u=rw,g=r,o=r"
    force: yes
  with_items:
  - "resolv.conf"
  tags:
  - conf

- name: "Update resolv.conf settings"
  shell:
    resolvconf -u
  tags:
  - conf

